services:

  postgres:
    image: postgres:15
    container_name: projet8_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airbyte:
    image: airbyte/airbyte:latest
    container_name: projet8_airbyte
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: